In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 7.0 MB/s 
     |████████████████████████████████| 596 kB 50.6 MB/s 
     |████████████████████████████████| 6.6 MB 44.4 MB/s 
     |████████████████████████████████| 101 kB 10.9 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from transformers import BertTokenizer, BertForNextSentencePrediction
import torch

In [3]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForNextSentencePrediction.from_pretrained('bert-base-uncased')


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForNextSentencePrediction: ['cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


# Next Sentence Prediction

In [4]:
text = 'I like cookies'

text2 = 'Joey went home to sleep'

In [5]:
inputs =  tokenizer(text, text2, return_tensors='pt')
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [6]:
inputs

{'input_ids': tensor([[  101,  1045,  2066, 16324,   102,  9558,  2253,  2188,  2000,  3637,
           102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [7]:
labels = torch.LongTensor([0])
labels

tensor([0])

In [8]:
outputs = model(**inputs, labels=labels)
outputs.keys()

odict_keys(['loss', 'logits'])

In [9]:
outputs.logits

tensor([[-0.7522,  2.0311]], grad_fn=<AddmmBackward0>)

In [10]:
torch.argmax(outputs.logits)

tensor(1)

### tensor(1) signifies the sentences are not related related to each other

In [11]:
# outputs.loss # To calculate loss of the model

In [12]:
# outputs.loss.item()

In [13]:
text = 'Joey like cookies'

text2 = 'Joey went home to sleep'

In [14]:
inputs =  tokenizer(text, text2, return_tensors='pt')
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [15]:

inputs

{'input_ids': tensor([[  101,  9558,  2066, 16324,   102,  9558,  2253,  2188,  2000,  3637,
           102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [16]:
labels = torch.LongTensor([0])
labels

tensor([0])

In [17]:
outputs = model(**inputs, labels=labels)
outputs.keys()

odict_keys(['loss', 'logits'])

In [18]:
outputs.logits

tensor([[ 6.0213, -5.7778]], grad_fn=<AddmmBackward0>)

In [19]:
torch.argmax(outputs.logits)

tensor(0)

### tensor(0) signifies the sentences are related to each other

# Masked Model

In [34]:
from transformers import pipeline

In [35]:
unmasker = pipeline('fill-mask', model='bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [22]:
unmasker("Hello I'm a [MASK] Scientist.")

[{'score': 0.18312019109725952,
  'token': 7596,
  'token_str': 'rocket',
  'sequence': "hello i'm a rocket scientist."},
 {'score': 0.139297217130661,
  'token': 5506,
  'token_str': 'mad',
  'sequence': "hello i'm a mad scientist."},
 {'score': 0.09731090068817139,
  'token': 8235,
  'token_str': 'brilliant',
  'sequence': "hello i'm a brilliant scientist."},
 {'score': 0.09597223252058029,
  'token': 2307,
  'token_str': 'great',
  'sequence': "hello i'm a great scientist."},
 {'score': 0.03696294128894806,
  'token': 2470,
  'token_str': 'research',
  'sequence': "hello i'm a research scientist."}]

In [36]:
unmasker("This is an [MASK].")

[{'score': 0.058144375681877136,
  'token': 12492,
  'token_str': 'illusion',
  'sequence': 'this is an illusion.'},
 {'score': 0.04691682383418083,
  'token': 7551,
  'token_str': 'experiment',
  'sequence': 'this is an experiment.'},
 {'score': 0.025287119671702385,
  'token': 2742,
  'token_str': 'example',
  'sequence': 'this is an example.'},
 {'score': 0.025256607681512833,
  'token': 4926,
  'token_str': 'accident',
  'sequence': 'this is an accident.'},
 {'score': 0.024686815217137337,
  'token': 7561,
  'token_str': 'error',
  'sequence': 'this is an error.'}]

# XLNet

In [4]:
!pip install sentencepiece
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 7.5 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [33]:
from transformers import XLNetTokenizer, XLNetLMHeadModel
from torch.nn import functional as F
import torch
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')
model = XLNetLMHeadModel.from_pretrained('xlnet-base-cased', return_dict = True)
text = "This is an " + tokenizer.mask_token
input = tokenizer.encode_plus(text, return_tensors = "pt")
output = model(**input).logits[:, -1, :]
softmax = F.softmax(output, dim = -1)
index = torch.argmax(softmax, dim = -1)
# print(index)
x = tokenizer.decode(index)
print(x)
new_sentence = text.replace(tokenizer.mask_token, x)
print(new_sentence)

####################
# Top Five choices #
####################
topFive = torch.argsort(softmax, dim=- 1, descending=True)
for i in topFive:
  # print(i[[j for j in range(0,5)]])
  x = (tokenizer.decode(i[[j for j in range(0,5)]])).split(" ")
  print(x)
for j in range(0,5):
  new_sentence = text.replace(tokenizer.mask_token, x[j])
  print(new_sentence)


chance
This is an chance
['chance', 'put', 'I', 'on', 'was']
This is an chance
This is an put
This is an I
This is an on
This is an was


In [46]:
from transformers import XLNetTokenizer, XLNetLMHeadModel
from torch.nn import functional as F
import torch
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')
model = XLNetLMHeadModel.from_pretrained('xlnet-base-cased', return_dict = True)
text = "This is an " + tokenizer.mask_token
input = tokenizer.encode_plus(text, return_tensors = "pt")
output = model(**input).logits[:, -1, :]
softmax = F.softmax(output, dim = -1)
index = torch.argmax(softmax, dim = -1)
# print(index)
x = tokenizer.decode(index)
print(x)
new_sentence = text.replace(tokenizer.mask_token, x)
print(new_sentence)

####################
#### All choices ###
####################

allChoices = torch.argsort(softmax, dim=- 1, descending=True)
for i in allChoices:
  print(i)
  x = (tokenizer.decode(i[[j for j in range(0,allChoices.size(dim=1))]])).split(" ")
  print(x)
for j in range(0,allChoices.size(dim=1)):
  new_sentence = text.replace(tokenizer.mask_token, x[j])
  print(new_sentence)


Streaming output truncated to the last 5000 lines.
This is an diversityivist
This is an peacekeepers
This is an Kashmir
This is an blanketsGoeither
This is an entities
This is an Rim
This is an schooner
This is an exploring
This is an cybermeanEER
This is an wagon
This is an Struscape
This is an fresco
This is an Bali
This is an Kabul
This is an mourning
This is an villain
This is an lungs
This is an empowerment
This is an priests
This is an improvised
This is an Settlement
This is an Scots
This is an scathingEEL
This is an Kellogg
This is an mutiumpearlier
This is an diplomacylaw
This is an refining
This is an Vil
This is an lease
This is an acreage
This is an Federer
This is an depths
This is an frivolousINEQui
This is an pregnanciesAXhander
This is an hydrocarbon
This is an misconception
This is an reloadmilk
This is an refuses
This is an Additionally
This is an McCu
This is an Virgil1,2
This is an MatIncreasingCAS
This is an Car
This is an calves
This is an Chung
This is an Ox
This

IndexError: ignored

# EQA Extractive Question Answering

In [3]:
from transformers import XLNetTokenizer 
from transformers import XLNetForQuestionAnsweringSimple
from torch.nn import functional as F
import torch
tokenizer = XLNetTokenizer.from_pretrained("xlnet-base-cased")
model = XLNetForQuestionAnsweringSimple.from_pretrained("xlnet-base-cased",return_dict = True)
question = "How many continents are there in the world?"
text = "There are 7 continents in the world."
inputs = tokenizer.encode_plus(question, text, return_tensors='pt')
output = model(**inputs)
start_max = torch.argmax(F.softmax(output.start_logits, dim = -1))
end_max = torch.argmax(F.softmax(output.end_logits, dim=-1)) + 1 
## add one because of python list indexing


Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetForQuestionAnsweringSimple: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetForQuestionAnsweringSimple from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLNetForQuestionAnsweringSimple from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of XLNetForQuestionAnsweringSimple were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['qa_outputs.weight', 'qa_outputs.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [4]:
answer = tokenizer.decode(inputs["input_ids"][0][start_max : end_max])
print(answer)

?<sep> There are 7 continents in the world.<sep>


# Multiple Choice Question Answering

In [5]:
from transformers import XLNetTokenizer, XLNetForMultipleChoice
from torch.nn import functional as F
import torch
tokenizer = XLNetTokenizer.from_pretrained("xlnet-base-cased")
model = XLNetForMultipleChoice.from_pretrained("xlnet-base-cased", return_dict = True)
prompt = "What is the capital of France?"
answers = ["Paris", "London", "Lyon", "Berlin"]
encoding = tokenizer([prompt, prompt, prompt, prompt], answers, return_tensors="pt", padding = True)
outputs = model(**{k: v.unsqueeze(0) for k, v in encoding.items()}) 
logits = outputs.logits
softmax = F.softmax(logits, dim = -1)
index = torch.argmax(softmax, dim = -1)

Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetForMultipleChoice: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetForMultipleChoice from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLNetForMultipleChoice from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of XLNetForMultipleChoice were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.weight', 'sequence_summary.summary.weight', 'logits_proj.bias', 'sequence_summary.summary.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [6]:
print("The correct answer is", answers[index])

The correct answer is Paris


# Comparing BERT Vs XLNet

In [11]:
# Bert
from transformers import pipeline
unmasker = pipeline('fill-mask', model='bert-base-uncased')
unmasker("United [MASK] is a country")

[{'score': 0.5351100564002991,
  'token': 2163,
  'token_str': 'states',
  'sequence': 'united states is a country'},
 {'score': 0.4369869828224182,
  'token': 2983,
  'token_str': 'kingdom',
  'sequence': 'united kingdom is a country'},
 {'score': 0.01750316470861435,
  'token': 3741,
  'token_str': 'nations',
  'sequence': 'united nations is a country'},
 {'score': 0.0007859703036956489,
  'token': 3163,
  'token_str': 'ireland',
  'sequence': 'united ireland is a country'},
 {'score': 0.00062819808954373,
  'token': 3088,
  'token_str': 'africa',
  'sequence': 'united africa is a country'}]

In [48]:
# XLNet
from transformers import XLNetTokenizer, XLNetLMHeadModel
from torch.nn import functional as F
import torch
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')
model = XLNetLMHeadModel.from_pretrained('xlnet-base-cased', return_dict = True)
text = "United " + tokenizer.mask_token + " is a country"
input = tokenizer.encode_plus(text, return_tensors = "pt")
output = model(**input).logits[:, -1, :]
softmax = F.softmax(output, dim = -1)
index = torch.argmax(softmax, dim = -1)
x = tokenizer.decode(index)
print(x)
new_sentence = text.replace(tokenizer.mask_token, x)
print(new_sentence)

and
United and is a country


In [49]:
####################
# Top Five choices #
####################
topFive = torch.argsort(softmax, dim=- 1, descending=True)
for i in topFive:
  # print(i[[j for j in range(0,5)]])
  x = (tokenizer.decode(i[[j for j in range(0,5)]])).split(" ")
  print(x)
for j in range(0,5):
  new_sentence = text.replace(tokenizer.mask_token, x[j])
  print(new_sentence)

['and', 'is', 'in', 'I', 'a']
United and is a country
United is is a country
United in is a country
United I is a country
United a is a country
